version: '3'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - 5173:5173
    networks:
      - kiruna-network
  backend:
    build:
     context: ./backend
    ports:
      - 3001:3001
    volumes:
      - backend_db:/app/db
    networks:
      - kiruna-network

networks:
  kiruna-network:
    driver: bridge
     
volumes:
  backend_db:
