POST http://localhost:3001/api/register
Content-Type: application/json

{
    "username": "noman",
    "password": "1234",
    "name": "" ,
    "surname": "Rafiq"
}

###

POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "noman",
    "password": "1234"
}

###
GET http://localhost:3001/api/check-login
Accept: application/json

###
POST http://localhost:3001/api/logout
Content-Type: application/json


###

PUT http://localhost:3001/api/addDescription
Content-Type: application/json

{
    "id": 1730712824791891,
    "title": "a",
    "description": "This document is a compilation of the responses to the survey 'What is your impression of Kiruna?' From the citizens' responses to this last part of the survey, it is evident that certain buildings, such as the Kiruna Church, the Hjalmar Lundbohmsgården, and the Town Hall, are considered of significant value to the population. The municipality views the experience of this survey positively, to the extent that over the years it will propose various consultation opportunities"
}

### Empty description
PUT http://localhost:3001/api/addDescription
Content-Type: application/json

{
    "id": 10,
    "title": "Construction of Block 1 begins (69)",
    "description": ""
}

########### get all documents
GET http://localhost:3001/api/documents
Accept: application/json

########### link documents
POST http://localhost:3001/api/linkDocuments
Content-Type: application/json

{
    "id1": 3,
    "id2": 4,
    "linkDate": "2022-09-27",
    "linkType": "direct consequence"
}

########### get document links
GET http://localhost:3001/api/documentLinks/7
Accept: application/json

########### update document links
PUT http://localhost:3001/api/links
Content-Type: application/json

{
    "idDocument1": 1,
    "idDocument2": 2,
    "newLinkDate": "2023-02-16",
    "newLinkType": "collateral consequence"
}

########## add document
POST http://localhost:3001/api/addDocument
Content-Type: application/json

{
    "title": "prova1",
    "stakeholders": "New Stakeholders",
    "scale": "1:1000",
    "issuanceDate": "2024-11-06",
    "type": "Report",
    "connections": "Updated connections",
    "language": "English",
    "pages": 10,
    "lat": 67.9128,
    "lon": 20.8060,
    "area": "",
    "description": "Updated description of the document"
}

########## add document - bad request
POST http://localhost:3001/api/addDocument
Content-Type: application/json

{
    "title": "prova1",
    "stakeholders": "New Stakeholders",
    "scale": "1:1000",
    "issuanceDate": "2024-11-06",
    "type": "Report",
    "connections": "Updated connections",
    "language": "English",
    "pages": 10,
    "lat": 67.9128,
    "lon": 20.8060,
    "area": "North Kiruna",
    "description": "Updated description of the document"
}

########## add document
POST http://localhost:3001/api/addDocument
Content-Type: application/json

{
    "title": "prova7",
    "stakeholders": "New Stakeholders",
    "scale": "1:1000",
    "issuanceDate": "2024-11-06",
    "type": "Report",
    "connections": "Updated connections",
    "language": "English",
    "pages": 10,
    "lat": null,
    "lon": null,
    "area": "North Kiruna",
    "description": "Updated description of the document"
}

########## update document
POST http://localhost:3001/api/updateDocument
Content-Type: application/json

{
    "id": 173082689802499,
    "title": "prova1",
    "stakeholders": "New Stakeholders",
    "scale": "1:1000",
    "issuanceDate": "2024-11-06",
    "type": "Report",
    "connections": "Updated connections",
    "language": "English",
    "pages": 10,
    "lat": 67.9128,
    "lon": 20.8060,
    "description": "Updated description of the document!!"
}

########## delete document 
POST http://localhost:3001/api/deleteDocument 
Content-Type: application/json

{
    "id": 1730826916158307
}

########## Upload file 
curl -X POST "http://localhost:3001/api/upload?documentId=10" \
  -F "resourceType=PDF" \
  -F "description=Sample PDF document for upload" \
  -F "resourceFile=@C:/Users/noman/Downloads/doc_18_info.pdf"
