POST http://localhost:3001/api/register
Content-Type: application/json

{
    "username": "noman",
    "password": "1234",
    "name": "" ,
    "surname": "Rafiq"
}

###

POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "noman",
    "password": "1234"
}

###
POST http://localhost:3001/api/logout
Content-Type: application/json
