POST http://localhost:3001/api/register
Content-Type: application/json

{
    "username": "noman",
    "password": "1234",
    "name": "" ,
    "surname": "Rafiq"
}

###

POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "noman",
    "password": "1234"
}

###
GET http://localhost:3001/api/check-login
Accept: application/json

###
POST http://localhost:3001/api/logout
Content-Type: application/json


###

PUT http://localhost:3001/api/addDescription
Content-Type: application/json

{
    "id": 1730712824791891,
    "title": "a",
    "description": "This document is a compilation of the responses to the survey 'What is your impression of Kiruna?' From the citizens' responses to this last part of the survey, it is evident that certain buildings, such as the Kiruna Church, the Hjalmar Lundbohmsgården, and the Town Hall, are considered of significant value to the population. The municipality views the experience of this survey positively, to the extent that over the years it will propose various consultation opportunities"
}

### Empty description
PUT http://localhost:3001/api/addDescription
Content-Type: application/json

{
    "id": 10,
    "title": "Construction of Block 1 begins (69)",
    "description": ""
}

########### get all documents
GET http://localhost:3001/api/documents
Accept: application/json

########### link documents
POST http://localhost:3001/api/linkDocuments
Content-Type: application/json

{
    "id1": 6,
    "id2": 7,
    "linkType": "Technical"
}

########### get document links
GET http://localhost:3001/api/documentLinks/10
Accept: application/json

########### update document links
PUT http://localhost:3001/api/updateLink
Content-Type: application/json

{
    "idDocument1": 5,
    "idDocument2": 4,
    "linkType": "Direct",
    "newLinkType": "Design"
}

### delete a link between two documents
DELETE http://localhost:3001/api/deleteLink
Content-Type: application/json

{
    "idDocument1": 4,
    "idDocument2": 5,
    "linkType": "Design"
}

########## add document
POST http://localhost:3001/api/addDocument
Content-Type: application/json

{
    "title": "prova2",
    "stakeholders": "New Stakeholders",
    "scale": "1:1000",
    "issuanceDate": "2024-11-06",
    "type": "Report",
    "connections": "Updated connections",
    "language": "English",
    "pages": 10,
    "lat": 67.9128,
    "lon": 20.8060,
    "area": "{\"type\":\"Polygon\",\"coordinates\":[[[20.8060,67.9128],[20.8060,67.9138],[20.8070,67.9138],[20.8070,67.9128],[20.8060,67.9128]]]}",
    "areaName": "Area 1",
    "description": "Description added"
}


########## add document - bad request
POST http://localhost:3001/api/addDocument
Content-Type: application/json

{
    "title": "prova1",
    "stakeholders": "New Stakeholders",
    "scale": "1:1000",
    "issuanceDate": "2024-11-06",
    "type": "Report",
    "connections": "Updated connections",
    "language": "English",
    "pages": 10,
    "lat": 67.9128,
    "lon": 20.8060,
    "area": "North Kiruna",
    "description": "Updated description of the document"
}

########## add document
POST http://localhost:3001/api/addDocument
Content-Type: application/json

{
    "title": "prova7",
    "stakeholders": "New Stakeholders",
    "scale": "1:1000",
    "issuanceDate": "2024-11-06",
    "type": "Report",
    "connections": "Updated connections",
    "language": "English",
    "pages": 10,
    "lat": null,
    "lon": null,
    "area": "North Kiruna",
    "description": "Updated description of the document"
}

########## update document
POST http://localhost:3001/api/updateDocument
Content-Type: application/json

{
    "id": 9,
     "title": "prova2",
    "stakeholders": "New Stakeholders",
    "scale": "1:1000",
    "issuanceDate": "2024-11-06",
    "type": "Report",
    "connections": "Updated connections",
    "language": "English",
    "pages": 10,
    "lat": 67.9128,
    "lon": 20.8060,
    "area": "{\"type\":\"Polygon\",\"coordinates\":[[[20.8060,67.9128],[20.8060,67.9138],[20.8070,67.9138],[20.8070,67.9128],[20.8060,67.9128]]]}",
    "areaName": "Area 2",
    "description": "New Updated description of the document"
}

########## delete document 
POST http://localhost:3001/api/deleteDocument 
Content-Type: application/json

{
    "id": 1730826916158307
}

  
#### Upload file 
curl -X POST "http://localhost:3001/api/upload?documentId=10&resourceType=pdf&description=Sample%20PDF%20File" \
  -H "Content-Type: application/octet-stream" \
  --data-binary @C:/Users/noman/Downloads/doc_18_info.pdf

### get files by documentId
GET http://localhost:3001/api/files/10 HTTP/1.1
Content-Type: application/json


### Download File
GET http://localhost:3001/api/download/1


### Delete file
curl -X DELETE "http://localhost:3001/api/delete?documentId=10&description=SamplePDFFile"


//-------------------

#### Upload file 
curl -X POST "http://localhost:3001/api/upload2?documentId=10&resourceType=pdf&description=Doc20" \
  -H "Content-Type: application/octet-stream" \
  --data-binary @C:/Users/noman/Downloads/doc_18_info.pdf
    --data-binary @C:/Users/noman/Downloads/doc_19_info.pdf


### Upload Multiple Files
curl -X POST "http://localhost:3001/api/upload2?documentId=10" \
  -F "files[]=@C:/Users/noman/Downloads/doc_19_info.pdf" \
  -F "files[]=@C:/Users/noman/Downloads/doc_18_info.pdf" \
  -F "resourceType=pdf" \
  -F "description=Document files"






### Test: Fetch Document Locations
GET http://localhost:3001/api/getDocumentLocations HTTP/1.1
Accept: application/json


###
GET http://localhost:3001/api/documents/stakeholders HTTP/1.1
Accept: application/json


### Test Case 1: Update Georeferencing with Latitude and Longitude
POST http://localhost:3001/api/updateDocumentGeoreference
Content-Type: application/json

{
  "id": 14,
  "lat": 67.123456,
  "lon": 20.987654
}

### Fetch georeferenced location for a valid document ID
GET http://localhost:3001/api/getDocumentLocation/7
Content-Type: application/json

### Fetch Area Names
GET http://localhost:3001/api/getAreaNames
Content-Type: application/json

### Update document position
GET http://localhost:3001/api/documents/1/position
Content-Type: application/json

### Update document position
PUT http://localhost:3001/api/documents/1/adjustPosition
Content-Type: application/json

{
    "x": 1,
    "y": 2
}


### Save Area
POST http://localhost:3001/api/saveArea
Content-Type: application/json

{
  "areaName": "Test Area",
  "coordinates": {
    "type": "Polygon",
    "coordinates": [
      [
        [19.5, 67.6],
        [21.0, 67.6],
        [21.0, 68.1],
        [19.5, 68.1],
        [19.5, 67.6]
      ]
    ]
  }
}

